FROM node:20-alpine
COPY ./src /app 
# RUN apk-get update -y && \
#     apk-get install -y nodejs && \
#     apk install npm && \
#     rm -rf /var/lib/apt/lists/*
WORKDIR /app
ENTRYPOINT ["npm"]
CMD ["run", "prod"]